branches:
  only:
    - master

dist: xenial

language: python

python:
  - "3.7"

addons:
  apt:
    packages:
    - mosquitto

install:
  - pip install -r requirements.txt
  - pip install ./

script:
  - pytest

after_success:
  - ci/travisscripts/tagdev.sh ci/deploy_key.enc $encrypted_aa97ff659f3d_key $encrypted_aa97ff659f3d_iv
